# WinLet Configuration - Advanced Logging Example
name = "advanced-logger-service"
display_name = "Advanced Logging Service"
description = "Demonstrates advanced logging capabilities similar to WinSW"

[process]
executable = "node"
arguments = "verbose-app.js"
working_directory = "C:\\DevOps"
shutdown_timeout_seconds = 30

[process.environment]
NODE_ENV = "production"
LOG_LEVEL = "debug"

# Enhanced logging configuration
[logging]
level = "Information"
log_to_console = true

# Log directory and mode
log_path = "C:\\Logs\\AdvancedService"
mode = "roll-by-size-time"

# Size-based rolling
size_threshold_kb = 5120  # 5MB threshold
keep_files = 10

# Time-based rolling
time_pattern = "yyyyMMdd"
auto_roll_at_time = "00:00:00"  # Roll at midnight

# Archive old logs
zip_older_than_days = 7
zip_date_format = "yyyyMM"

# Separate stdout and stderr
separate_error_log = true
stdout_log_file = "app-output.log"
stderr_log_file = "app-errors.log"

[restart]
policy = "OnFailure"
delay_seconds = 10
max_attempts = 5
window_seconds = 600

# Service account configuration
[service_account]
username = "NT AUTHORITY\\NetworkService"
allow_service_logon = true 