# WinLet Configuration - Simple Logging Modes
name = "simple-logger"
display_name = "Simple Logger Service"
description = "Basic logging configuration examples"

[process]
executable = "ping"
arguments = "localhost -t"
working_directory = "C:\\Windows\\System32"

# Simple append mode (default)
[logging]
level = "Information"
log_to_console = true
log_path = "C:\\Logs\\SimpleService"
mode = "append"

[restart]
policy = "Always"
delay_seconds = 5

# Alternative logging modes (comment/uncomment to test):

# Reset mode - truncate logs on service start
# [logging]
# mode = "reset"
# log_path = "C:\\Logs\\SimpleService"

# No logging - discard all output
# [logging]
# mode = "none"

# Roll by size only
# [logging]
# mode = "roll-by-size"
# size_threshold_kb = 1024  # 1MB
# keep_files = 5
# log_path = "C:\\Logs\\SimpleService"

# Roll by time only
# [logging]
# mode = "roll-by-time"
# time_pattern = "yyyyMMdd"
# auto_roll_at_time = "12:00:00"  # Roll at noon
# log_path = "C:\\Logs\\SimpleService" 