[service]
name = "my-web-app"
display_name = "My Web Application"
description = "A Node.js web application"

[process]
executable = "node"
arguments = "app.js"
working_directory = "C:\\Apps\\MyWebApp"

[process.environment]
NODE_ENV = "production"
PORT = "3000"

[logging]
level = "Information"
log_to_console = true
log_path = "C:\\Logs\\MyWebApp"

[restart]
policy = "OnFailure"
max_attempts = 3